2023-06-28 08:35:06,036,36,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========== process HighD_highway01_50_4_4_pred_step_10  is running! ===========
2023-06-28 08:35:06,302,302,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========== finish load route and depart ========
      height  width       x  ...      y  yAcceleration  yVelocity
0       1.92   4.75  344.47  ...  26.07           0.07       0.05
1       1.92   4.75  345.79  ...  26.07           0.06       0.05
2       1.92   4.75  347.11  ...  26.07           0.06       0.06
3       1.92   4.75  348.42  ...  26.07           0.06       0.06
4       1.92   4.75  349.74  ...  26.07           0.06       0.06
...      ...    ...     ...  ...    ...            ...        ...
8309    2.02   4.55    4.89  ...  21.91           0.01      -0.18
8310    2.02   4.55    6.42  ...  21.90           0.01      -0.18
8311    2.02   4.55    7.98  ...  21.89           0.01      -0.18
8312    2.02   4.55    9.56  ...  21.88           0.02      -0.18
8313    2.02   4.55   11.16  ...  21.87           0.02      -0.18

[5937 rows x 8 columns]
feat_veh height
feat_veh width
feat_veh x
feat_veh xAcceleration
feat_veh xVelocity
feat_veh y
feat_veh yAcceleration
feat_veh yVelocity
feat_lane speed_avg
feat_lane width
feat_lane x
feat_lane y
2023-06-28 08:35:08,833,833,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========= finish load graph =========
2023-06-28 08:35:14,591,591,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========= 10_50_1 =========
2023-06-28 08:35:15,557,557,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========== finish generate generator rule ==========

  0%|          | 0/10 [00:00<?, ?it/s]2023-06-28 08:35:15,560,560,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::--------- current ep is 0 --------
2023-06-28 08:35:15,562,562,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========= start generate dataset =======
2023-06-28 08:35:15,565,565,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========== finish generate dataset =======
2023-06-28 08:35:15,568,568,INFO,scenario_HighDtest_data_highway01_dim_50_n_heads_4_n_layer_4::========= start training =======

  0%|          | 0/10 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/home/pai/envs/tsim_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pai/envs/tsim_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/transworld_hd.py", line 272, in <module>
    run(args.scenario,args.train_data, args.training_step, args.pred_step, args.hid_dim, args.n_head, args.n_layer, device)
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/transworld_hd.py", line 213, in run
    loss_lst = train(timestamps, graph, batch_size, num_workers, encoder, generator, veh_route, loss_fcn, optimizer, logger, device)
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/transworld_hd.py", line 56, in train
    actions, pred_graph = generator([seed_node_n_time], cur_graph, node_repr, veh_route)
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/game/model/generator.py", line 177, in forward
    node_states, actions = self.generate_actions_and_state(
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/game/model/generator.py", line 132, in generate_actions_and_state
    node_states, node_state_scaled = self.generate_state(node_repr)
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/game/model/generator.py", line 152, in generate_state
    return node_state, node_state_scaled
UnboundLocalError: local variable 'node_state_scaled' referenced before assignment
2023-06-28 08:53:15,731,731,INFO,scenario_bologna_cleantest_data_test500_dim_50_n_heads_4_n_layer_4::========== process bologna_clean_test500_50_4_4_pred_step_10  is running! ===========
Traceback (most recent call last):
  File "/home/pai/envs/tsim_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pai/envs/tsim_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/transworld_exp.py", line 269, in <module>
    run(args.scenario,args.train_data, args.training_step, args.pred_step, args.hid_dim, args.n_head, args.n_layer, device)
  File "/mnt/workspace/wangding/Desktop/TransWorldNG/transworld/transworld_exp.py", line 137, in run
    node_all = pd.read_csv(train_data_dir / "node_all.csv")
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/pai/envs/tsim_env/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/workspace/wangding/Desktop/TransWorldNG/experiment/bologna_clean/data/test500/train_data/node_all.csv'
/home/pai/envs/tsim_env/bin/python: No module named sumo_exp
